# Generated by Django 4.0 on 2022-05-23 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Organization type description')),
            ],
            options={
                'verbose_name': 'OrgType',
                'verbose_name_plural': 'OrgTypes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, help_text='Personal image of the consultant', null=True, upload_to='images/')),
                ('title', models.CharField(help_text='Title of the organization.', max_length=300, unique=True, verbose_name='Title')),
                ('type', models.ForeignKey(blank=True, help_text='Type of the organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.orgtype')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['title'],
            },
        ),
    ]
