# Generated by Django 4.0 on 2022-05-23 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Competence')),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Occupation')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sphere')),
            ],
            options={
                'verbose_name': 'Sphere',
                'verbose_name_plural': 'Spheres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Language')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consultants.languagelevel', verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, help_text='Personal image of the consultant', null=True, upload_to='images/')),
                ('fullname', models.CharField(help_text='Full name of the consultant. If similar with other one add middle name', max_length=100, unique=True, verbose_name='Full name')),
                ('age', models.PositiveIntegerField(default=0, help_text='Current age of the consultant', verbose_name='Age')),
                ('email', models.CharField(blank=True, help_text='Active email of the consultant', max_length=100, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Active phone number of the consultant', max_length=100, null=True, unique=True, verbose_name='Phone')),
                ('experience', models.TextField(blank=True, help_text='Brief information on the previous and current positions of the consultant', null=True, verbose_name='Experience')),
                ('education', models.TextField(blank=True, help_text='Brief information on the academic background of the consultant', null=True, verbose_name='Education')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('type', models.CharField(blank=True, choices=[('international', 'International'), ('local', 'Local')], help_text='International or local consultant?', max_length=20, null=True, verbose_name='Type')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(blank=True, default=False, help_text='Check if the given information is verified by the consultant.', null=True, verbose_name='Verified')),
                ('competences', models.ManyToManyField(blank=True, to='consultants.Competence', verbose_name='Competences')),
                ('languages', models.ManyToManyField(blank=True, to='consultants.Language', verbose_name='Languages')),
                ('occupation', models.ForeignKey(blank=True, help_text='Current professional occupation', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultants.occupation')),
                ('sphere', models.ForeignKey(blank=True, help_text='Professional sphere', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultants.sphere')),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
                'ordering': ['fullname'],
            },
        ),
    ]
