# Generated by Django 4.0 on 2022-05-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Current affiliated organization.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
